emails:
  - email: "bounthongv@gmail.com"
    imap_host: "imap.gmail.com"
    imap_port: 993
    password: "pckq vqbi dlnd bsmm"
    enabled: true

  - email: "bounthongvxy@gmail.com"
    imap_host: "imap.gmail.com"
    imap_port: 993
    password: "vmwh xzcd mdrj oepk"
    enabled: true

  - email: "boonthongvxy@gmail.com"
    imap_host: "imap.gmail.com"
    imap_port: 993
    password: "ceye ilxb bhwb lvte"
    enabled: true

telegram:
  bot_token: "8569644462:AAEnNgDBLkbAlKrhgkyZEV4cRda2tDlrOvI"
  chat_id: 7252862418

openrouter:
  api_key: "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"

deepseek:
  api_key: ""

gemini:
  api_key: "AIzaSyBRG8MlMc5NEh9nFDCpqiZVzlvntzQ-ZJQ"
